volumes:
  db-data:

services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  jaeger:
    image: jaegertracing/all-in-one
    ports:
      # frontend
      - "16686:16686"
      - "14268"
      - "14250"
    environment:
      - METRICS_STORAGE_TYPE=prometheus
      - PROMETHEUS_QUERY_SUPPORT_SPANMETRICS_CONNECTOR=true
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
    depends_on:
      - jaeger
