name: ci

on:
  pull_request:
    branches:
      - main
    paths:
      - package.json
      - src/**
      - e2e/**
      - .github/workflows/ci.yml
      - Dockerfile
  push:
    branches:
      - main
    paths:
      - package.json
      - src/**
      - e2e/**
      - .github/workflows/ci.yml
      - Dockerfile

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - run: pnpm lint
      - run: npx biome check . && npx prettier --check './**/*.{md,yml}'
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/setup-db
      - run: pnpm build
  # start: docker #
  build-docker:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SITE_URL: http://localhost:3000
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/setup-db
      - run: |
          docker build \
            -t app \
            -f Dockerfile \
            --add-host=host.docker.internal:host-gateway \
            --build-arg DATABASE_URL=${{env.DATABASE_URL}} \
            --build-arg DATABASE_HOST=${{env.DATABASE_HOST}} \
            --build-arg NEXTAUTH_SECRET=${{env.NEXTAUTH_SECRET}} \
            --build-arg NEXT_PUBLIC_SITE_URL=${{env.NEXT_PUBLIC_SITE_URL}} \
            .
        env:
          DATABASE_HOST: host.docker.internal
          DATABASE_URL: postgresql://dev:1234@0.0.0.0:5432/dev?schema=public
          NEXTAUTH_SECRET: TKDdLVjf7cTyTs5oWVpv04senu6fia4RGQbYHRQIR5Q=
      - run: docker run -d -p 3000:3000 app
      - run: |
          until $(curl --output /dev/null --silent --fail ${{env.NEXT_PUBLIC_SITE_URL}}); do
            printf '!'
            sleep 1
          done
        timeout-minutes: 1
  # end: docker #
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/setup-db
        with:
          run_db: false
      - run: pnpm test
  # start: e2e #
  e2e-test:
    runs-on: ubuntu-latest
    env:
      NEXTAUTH_SECRET: UfxvOS6HetHOFkL44YTITYgc0DOuOlz5TBp3jkbnZ3w=
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/setup-db
        with:
          run_db: false
      - run: pnpm exec playwright install chromium
      - run: pnpm build:test
      - run: pnpm test:e2e
  # end: e2e #
